// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: satellite_Earth_simulation.proto

#include "satellite_Earth_simulation.pb.h"
#include "satellite_Earth_simulation.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace SatelliteEarthSimulation {

static const char* SatelliteEarthSimulationService_method_names[] = {
  "/SatelliteEarthSimulation.SatelliteEarthSimulationService/RunSimulation",
};

std::unique_ptr< SatelliteEarthSimulationService::Stub> SatelliteEarthSimulationService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SatelliteEarthSimulationService::Stub> stub(new SatelliteEarthSimulationService::Stub(channel, options));
  return stub;
}

SatelliteEarthSimulationService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RunSimulation_(SatelliteEarthSimulationService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SatelliteEarthSimulationService::Stub::RunSimulation(::grpc::ClientContext* context, const ::SatelliteEarthSimulation::SimRequest& request, ::SatelliteEarthSimulation::SimResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::SatelliteEarthSimulation::SimRequest, ::SatelliteEarthSimulation::SimResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RunSimulation_, context, request, response);
}

void SatelliteEarthSimulationService::Stub::async::RunSimulation(::grpc::ClientContext* context, const ::SatelliteEarthSimulation::SimRequest* request, ::SatelliteEarthSimulation::SimResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::SatelliteEarthSimulation::SimRequest, ::SatelliteEarthSimulation::SimResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RunSimulation_, context, request, response, std::move(f));
}

void SatelliteEarthSimulationService::Stub::async::RunSimulation(::grpc::ClientContext* context, const ::SatelliteEarthSimulation::SimRequest* request, ::SatelliteEarthSimulation::SimResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RunSimulation_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::SatelliteEarthSimulation::SimResponse>* SatelliteEarthSimulationService::Stub::PrepareAsyncRunSimulationRaw(::grpc::ClientContext* context, const ::SatelliteEarthSimulation::SimRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::SatelliteEarthSimulation::SimResponse, ::SatelliteEarthSimulation::SimRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RunSimulation_, context, request);
}

::grpc::ClientAsyncResponseReader< ::SatelliteEarthSimulation::SimResponse>* SatelliteEarthSimulationService::Stub::AsyncRunSimulationRaw(::grpc::ClientContext* context, const ::SatelliteEarthSimulation::SimRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRunSimulationRaw(context, request, cq);
  result->StartCall();
  return result;
}

SatelliteEarthSimulationService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SatelliteEarthSimulationService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SatelliteEarthSimulationService::Service, ::SatelliteEarthSimulation::SimRequest, ::SatelliteEarthSimulation::SimResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SatelliteEarthSimulationService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::SatelliteEarthSimulation::SimRequest* req,
             ::SatelliteEarthSimulation::SimResponse* resp) {
               return service->RunSimulation(ctx, req, resp);
             }, this)));
}

SatelliteEarthSimulationService::Service::~Service() {
}

::grpc::Status SatelliteEarthSimulationService::Service::RunSimulation(::grpc::ServerContext* context, const ::SatelliteEarthSimulation::SimRequest* request, ::SatelliteEarthSimulation::SimResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace SatelliteEarthSimulation

