// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: satellite_Earth_simulation.proto
#ifndef GRPC_satellite_5fEarth_5fsimulation_2eproto__INCLUDED
#define GRPC_satellite_5fEarth_5fsimulation_2eproto__INCLUDED

#include "satellite_Earth_simulation.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace SatelliteEarthSimulation {

class SatelliteEarthSimulationService final {
 public:
  static constexpr char const* service_full_name() {
    return "SatelliteEarthSimulation.SatelliteEarthSimulationService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status RunSimulation(::grpc::ClientContext* context, const ::SatelliteEarthSimulation::SimRequest& request, ::SatelliteEarthSimulation::SimResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SatelliteEarthSimulation::SimResponse>> AsyncRunSimulation(::grpc::ClientContext* context, const ::SatelliteEarthSimulation::SimRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SatelliteEarthSimulation::SimResponse>>(AsyncRunSimulationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SatelliteEarthSimulation::SimResponse>> PrepareAsyncRunSimulation(::grpc::ClientContext* context, const ::SatelliteEarthSimulation::SimRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SatelliteEarthSimulation::SimResponse>>(PrepareAsyncRunSimulationRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void RunSimulation(::grpc::ClientContext* context, const ::SatelliteEarthSimulation::SimRequest* request, ::SatelliteEarthSimulation::SimResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RunSimulation(::grpc::ClientContext* context, const ::SatelliteEarthSimulation::SimRequest* request, ::SatelliteEarthSimulation::SimResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::SatelliteEarthSimulation::SimResponse>* AsyncRunSimulationRaw(::grpc::ClientContext* context, const ::SatelliteEarthSimulation::SimRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::SatelliteEarthSimulation::SimResponse>* PrepareAsyncRunSimulationRaw(::grpc::ClientContext* context, const ::SatelliteEarthSimulation::SimRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status RunSimulation(::grpc::ClientContext* context, const ::SatelliteEarthSimulation::SimRequest& request, ::SatelliteEarthSimulation::SimResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SatelliteEarthSimulation::SimResponse>> AsyncRunSimulation(::grpc::ClientContext* context, const ::SatelliteEarthSimulation::SimRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SatelliteEarthSimulation::SimResponse>>(AsyncRunSimulationRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SatelliteEarthSimulation::SimResponse>> PrepareAsyncRunSimulation(::grpc::ClientContext* context, const ::SatelliteEarthSimulation::SimRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SatelliteEarthSimulation::SimResponse>>(PrepareAsyncRunSimulationRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void RunSimulation(::grpc::ClientContext* context, const ::SatelliteEarthSimulation::SimRequest* request, ::SatelliteEarthSimulation::SimResponse* response, std::function<void(::grpc::Status)>) override;
      void RunSimulation(::grpc::ClientContext* context, const ::SatelliteEarthSimulation::SimRequest* request, ::SatelliteEarthSimulation::SimResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::SatelliteEarthSimulation::SimResponse>* AsyncRunSimulationRaw(::grpc::ClientContext* context, const ::SatelliteEarthSimulation::SimRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::SatelliteEarthSimulation::SimResponse>* PrepareAsyncRunSimulationRaw(::grpc::ClientContext* context, const ::SatelliteEarthSimulation::SimRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RunSimulation_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RunSimulation(::grpc::ServerContext* context, const ::SatelliteEarthSimulation::SimRequest* request, ::SatelliteEarthSimulation::SimResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RunSimulation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RunSimulation() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RunSimulation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunSimulation(::grpc::ServerContext* /*context*/, const ::SatelliteEarthSimulation::SimRequest* /*request*/, ::SatelliteEarthSimulation::SimResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRunSimulation(::grpc::ServerContext* context, ::SatelliteEarthSimulation::SimRequest* request, ::grpc::ServerAsyncResponseWriter< ::SatelliteEarthSimulation::SimResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RunSimulation<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_RunSimulation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RunSimulation() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::SatelliteEarthSimulation::SimRequest, ::SatelliteEarthSimulation::SimResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::SatelliteEarthSimulation::SimRequest* request, ::SatelliteEarthSimulation::SimResponse* response) { return this->RunSimulation(context, request, response); }));}
    void SetMessageAllocatorFor_RunSimulation(
        ::grpc::MessageAllocator< ::SatelliteEarthSimulation::SimRequest, ::SatelliteEarthSimulation::SimResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::SatelliteEarthSimulation::SimRequest, ::SatelliteEarthSimulation::SimResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RunSimulation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunSimulation(::grpc::ServerContext* /*context*/, const ::SatelliteEarthSimulation::SimRequest* /*request*/, ::SatelliteEarthSimulation::SimResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RunSimulation(
      ::grpc::CallbackServerContext* /*context*/, const ::SatelliteEarthSimulation::SimRequest* /*request*/, ::SatelliteEarthSimulation::SimResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_RunSimulation<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RunSimulation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RunSimulation() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RunSimulation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunSimulation(::grpc::ServerContext* /*context*/, const ::SatelliteEarthSimulation::SimRequest* /*request*/, ::SatelliteEarthSimulation::SimResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RunSimulation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RunSimulation() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RunSimulation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunSimulation(::grpc::ServerContext* /*context*/, const ::SatelliteEarthSimulation::SimRequest* /*request*/, ::SatelliteEarthSimulation::SimResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRunSimulation(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RunSimulation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RunSimulation() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RunSimulation(context, request, response); }));
    }
    ~WithRawCallbackMethod_RunSimulation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RunSimulation(::grpc::ServerContext* /*context*/, const ::SatelliteEarthSimulation::SimRequest* /*request*/, ::SatelliteEarthSimulation::SimResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RunSimulation(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RunSimulation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RunSimulation() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::SatelliteEarthSimulation::SimRequest, ::SatelliteEarthSimulation::SimResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::SatelliteEarthSimulation::SimRequest, ::SatelliteEarthSimulation::SimResponse>* streamer) {
                       return this->StreamedRunSimulation(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RunSimulation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RunSimulation(::grpc::ServerContext* /*context*/, const ::SatelliteEarthSimulation::SimRequest* /*request*/, ::SatelliteEarthSimulation::SimResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRunSimulation(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::SatelliteEarthSimulation::SimRequest,::SatelliteEarthSimulation::SimResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RunSimulation<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RunSimulation<Service > StreamedService;
};

}  // namespace SatelliteEarthSimulation


#endif  // GRPC_satellite_5fEarth_5fsimulation_2eproto__INCLUDED
