// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Earth_simulation.proto
#ifndef GRPC_Earth_5fsimulation_2eproto__INCLUDED
#define GRPC_Earth_5fsimulation_2eproto__INCLUDED

#include "Earth_simulation.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace EarthSimulation {

class EarthSimulationService final {
 public:
  static constexpr char const* service_full_name() {
    return "EarthSimulation.EarthSimulationService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SendEarthData(::grpc::ClientContext* context, const ::EarthSimulation::EarthRequest& request, ::EarthSimulation::EarthResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::EarthSimulation::EarthResponse>> AsyncSendEarthData(::grpc::ClientContext* context, const ::EarthSimulation::EarthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::EarthSimulation::EarthResponse>>(AsyncSendEarthDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::EarthSimulation::EarthResponse>> PrepareAsyncSendEarthData(::grpc::ClientContext* context, const ::EarthSimulation::EarthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::EarthSimulation::EarthResponse>>(PrepareAsyncSendEarthDataRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SendEarthData(::grpc::ClientContext* context, const ::EarthSimulation::EarthRequest* request, ::EarthSimulation::EarthResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendEarthData(::grpc::ClientContext* context, const ::EarthSimulation::EarthRequest* request, ::EarthSimulation::EarthResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::EarthSimulation::EarthResponse>* AsyncSendEarthDataRaw(::grpc::ClientContext* context, const ::EarthSimulation::EarthRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::EarthSimulation::EarthResponse>* PrepareAsyncSendEarthDataRaw(::grpc::ClientContext* context, const ::EarthSimulation::EarthRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SendEarthData(::grpc::ClientContext* context, const ::EarthSimulation::EarthRequest& request, ::EarthSimulation::EarthResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::EarthSimulation::EarthResponse>> AsyncSendEarthData(::grpc::ClientContext* context, const ::EarthSimulation::EarthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::EarthSimulation::EarthResponse>>(AsyncSendEarthDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::EarthSimulation::EarthResponse>> PrepareAsyncSendEarthData(::grpc::ClientContext* context, const ::EarthSimulation::EarthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::EarthSimulation::EarthResponse>>(PrepareAsyncSendEarthDataRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SendEarthData(::grpc::ClientContext* context, const ::EarthSimulation::EarthRequest* request, ::EarthSimulation::EarthResponse* response, std::function<void(::grpc::Status)>) override;
      void SendEarthData(::grpc::ClientContext* context, const ::EarthSimulation::EarthRequest* request, ::EarthSimulation::EarthResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::EarthSimulation::EarthResponse>* AsyncSendEarthDataRaw(::grpc::ClientContext* context, const ::EarthSimulation::EarthRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::EarthSimulation::EarthResponse>* PrepareAsyncSendEarthDataRaw(::grpc::ClientContext* context, const ::EarthSimulation::EarthRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SendEarthData_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SendEarthData(::grpc::ServerContext* context, const ::EarthSimulation::EarthRequest* request, ::EarthSimulation::EarthResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SendEarthData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendEarthData() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SendEarthData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendEarthData(::grpc::ServerContext* /*context*/, const ::EarthSimulation::EarthRequest* /*request*/, ::EarthSimulation::EarthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendEarthData(::grpc::ServerContext* context, ::EarthSimulation::EarthRequest* request, ::grpc::ServerAsyncResponseWriter< ::EarthSimulation::EarthResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SendEarthData<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SendEarthData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendEarthData() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::EarthSimulation::EarthRequest, ::EarthSimulation::EarthResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::EarthSimulation::EarthRequest* request, ::EarthSimulation::EarthResponse* response) { return this->SendEarthData(context, request, response); }));}
    void SetMessageAllocatorFor_SendEarthData(
        ::grpc::MessageAllocator< ::EarthSimulation::EarthRequest, ::EarthSimulation::EarthResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::EarthSimulation::EarthRequest, ::EarthSimulation::EarthResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendEarthData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendEarthData(::grpc::ServerContext* /*context*/, const ::EarthSimulation::EarthRequest* /*request*/, ::EarthSimulation::EarthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendEarthData(
      ::grpc::CallbackServerContext* /*context*/, const ::EarthSimulation::EarthRequest* /*request*/, ::EarthSimulation::EarthResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SendEarthData<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SendEarthData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendEarthData() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SendEarthData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendEarthData(::grpc::ServerContext* /*context*/, const ::EarthSimulation::EarthRequest* /*request*/, ::EarthSimulation::EarthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendEarthData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendEarthData() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SendEarthData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendEarthData(::grpc::ServerContext* /*context*/, const ::EarthSimulation::EarthRequest* /*request*/, ::EarthSimulation::EarthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendEarthData(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendEarthData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendEarthData() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendEarthData(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendEarthData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendEarthData(::grpc::ServerContext* /*context*/, const ::EarthSimulation::EarthRequest* /*request*/, ::EarthSimulation::EarthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendEarthData(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendEarthData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendEarthData() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::EarthSimulation::EarthRequest, ::EarthSimulation::EarthResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::EarthSimulation::EarthRequest, ::EarthSimulation::EarthResponse>* streamer) {
                       return this->StreamedSendEarthData(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendEarthData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendEarthData(::grpc::ServerContext* /*context*/, const ::EarthSimulation::EarthRequest* /*request*/, ::EarthSimulation::EarthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendEarthData(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::EarthSimulation::EarthRequest,::EarthSimulation::EarthResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SendEarthData<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SendEarthData<Service > StreamedService;
};

}  // namespace EarthSimulation


#endif  // GRPC_Earth_5fsimulation_2eproto__INCLUDED
