// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Earth_simulation.proto

#include "Earth_simulation.pb.h"
#include "Earth_simulation.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace EarthSimulation {

static const char* EarthSimulationService_method_names[] = {
  "/EarthSimulation.EarthSimulationService/SendEarthData",
};

std::unique_ptr< EarthSimulationService::Stub> EarthSimulationService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< EarthSimulationService::Stub> stub(new EarthSimulationService::Stub(channel, options));
  return stub;
}

EarthSimulationService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendEarthData_(EarthSimulationService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status EarthSimulationService::Stub::SendEarthData(::grpc::ClientContext* context, const ::EarthSimulation::EarthRequest& request, ::EarthSimulation::EarthResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::EarthSimulation::EarthRequest, ::EarthSimulation::EarthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendEarthData_, context, request, response);
}

void EarthSimulationService::Stub::async::SendEarthData(::grpc::ClientContext* context, const ::EarthSimulation::EarthRequest* request, ::EarthSimulation::EarthResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::EarthSimulation::EarthRequest, ::EarthSimulation::EarthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendEarthData_, context, request, response, std::move(f));
}

void EarthSimulationService::Stub::async::SendEarthData(::grpc::ClientContext* context, const ::EarthSimulation::EarthRequest* request, ::EarthSimulation::EarthResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendEarthData_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::EarthSimulation::EarthResponse>* EarthSimulationService::Stub::PrepareAsyncSendEarthDataRaw(::grpc::ClientContext* context, const ::EarthSimulation::EarthRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::EarthSimulation::EarthResponse, ::EarthSimulation::EarthRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendEarthData_, context, request);
}

::grpc::ClientAsyncResponseReader< ::EarthSimulation::EarthResponse>* EarthSimulationService::Stub::AsyncSendEarthDataRaw(::grpc::ClientContext* context, const ::EarthSimulation::EarthRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendEarthDataRaw(context, request, cq);
  result->StartCall();
  return result;
}

EarthSimulationService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EarthSimulationService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< EarthSimulationService::Service, ::EarthSimulation::EarthRequest, ::EarthSimulation::EarthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](EarthSimulationService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::EarthSimulation::EarthRequest* req,
             ::EarthSimulation::EarthResponse* resp) {
               return service->SendEarthData(ctx, req, resp);
             }, this)));
}

EarthSimulationService::Service::~Service() {
}

::grpc::Status EarthSimulationService::Service::SendEarthData(::grpc::ServerContext* context, const ::EarthSimulation::EarthRequest* request, ::EarthSimulation::EarthResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace EarthSimulation

