// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: Earth_simulation.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EarthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*EarthRequest_Nodes  `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EarthRequest) Reset() {
	*x = EarthRequest{}
	mi := &file_Earth_simulation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EarthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EarthRequest) ProtoMessage() {}

func (x *EarthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Earth_simulation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EarthRequest.ProtoReflect.Descriptor instead.
func (*EarthRequest) Descriptor() ([]byte, []int) {
	return file_Earth_simulation_proto_rawDescGZIP(), []int{0}
}

func (x *EarthRequest) GetNodes() []*EarthRequest_Nodes {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type EarthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frames        []*EarthResponse_Frame `protobuf:"bytes,1,rep,name=frames,proto3" json:"frames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EarthResponse) Reset() {
	*x = EarthResponse{}
	mi := &file_Earth_simulation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EarthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EarthResponse) ProtoMessage() {}

func (x *EarthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Earth_simulation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EarthResponse.ProtoReflect.Descriptor instead.
func (*EarthResponse) Descriptor() ([]byte, []int) {
	return file_Earth_simulation_proto_rawDescGZIP(), []int{1}
}

func (x *EarthResponse) GetFrames() []*EarthResponse_Frame {
	if x != nil {
		return x.Frames
	}
	return nil
}

type EarthRequest_Nodes struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	TRelS         float64                 `protobuf:"fixed64,1,opt,name=t_rel_s,json=tRelS,proto3" json:"t_rel_s,omitempty"`
	Geo           *EarthRequest_Nodes_Geo `protobuf:"bytes,2,opt,name=geo,proto3" json:"geo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EarthRequest_Nodes) Reset() {
	*x = EarthRequest_Nodes{}
	mi := &file_Earth_simulation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EarthRequest_Nodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EarthRequest_Nodes) ProtoMessage() {}

func (x *EarthRequest_Nodes) ProtoReflect() protoreflect.Message {
	mi := &file_Earth_simulation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EarthRequest_Nodes.ProtoReflect.Descriptor instead.
func (*EarthRequest_Nodes) Descriptor() ([]byte, []int) {
	return file_Earth_simulation_proto_rawDescGZIP(), []int{0, 0}
}

func (x *EarthRequest_Nodes) GetTRelS() float64 {
	if x != nil {
		return x.TRelS
	}
	return 0
}

func (x *EarthRequest_Nodes) GetGeo() *EarthRequest_Nodes_Geo {
	if x != nil {
		return x.Geo
	}
	return nil
}

type EarthRequest_Nodes_Geo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LatDeg        float64                `protobuf:"fixed64,1,opt,name=lat_deg,json=latDeg,proto3" json:"lat_deg,omitempty"`
	LonDeg        float64                `protobuf:"fixed64,2,opt,name=lon_deg,json=lonDeg,proto3" json:"lon_deg,omitempty"`
	AltKm         float64                `protobuf:"fixed64,3,opt,name=alt_km,json=altKm,proto3" json:"alt_km,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EarthRequest_Nodes_Geo) Reset() {
	*x = EarthRequest_Nodes_Geo{}
	mi := &file_Earth_simulation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EarthRequest_Nodes_Geo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EarthRequest_Nodes_Geo) ProtoMessage() {}

func (x *EarthRequest_Nodes_Geo) ProtoReflect() protoreflect.Message {
	mi := &file_Earth_simulation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EarthRequest_Nodes_Geo.ProtoReflect.Descriptor instead.
func (*EarthRequest_Nodes_Geo) Descriptor() ([]byte, []int) {
	return file_Earth_simulation_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *EarthRequest_Nodes_Geo) GetLatDeg() float64 {
	if x != nil {
		return x.LatDeg
	}
	return 0
}

func (x *EarthRequest_Nodes_Geo) GetLonDeg() float64 {
	if x != nil {
		return x.LonDeg
	}
	return 0
}

func (x *EarthRequest_Nodes_Geo) GetAltKm() float64 {
	if x != nil {
		return x.AltKm
	}
	return 0
}

type EarthResponse_Frame struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	TRelS         float64                  `protobuf:"fixed64,1,opt,name=t_rel_s,json=tRelS,proto3" json:"t_rel_s,omitempty"`
	Geo           *EarthResponse_Frame_Geo `protobuf:"bytes,2,opt,name=geo,proto3" json:"geo,omitempty"`
	Mag           *EarthResponse_Frame_Mag `protobuf:"bytes,3,opt,name=mag,proto3" json:"mag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EarthResponse_Frame) Reset() {
	*x = EarthResponse_Frame{}
	mi := &file_Earth_simulation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EarthResponse_Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EarthResponse_Frame) ProtoMessage() {}

func (x *EarthResponse_Frame) ProtoReflect() protoreflect.Message {
	mi := &file_Earth_simulation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EarthResponse_Frame.ProtoReflect.Descriptor instead.
func (*EarthResponse_Frame) Descriptor() ([]byte, []int) {
	return file_Earth_simulation_proto_rawDescGZIP(), []int{1, 0}
}

func (x *EarthResponse_Frame) GetTRelS() float64 {
	if x != nil {
		return x.TRelS
	}
	return 0
}

func (x *EarthResponse_Frame) GetGeo() *EarthResponse_Frame_Geo {
	if x != nil {
		return x.Geo
	}
	return nil
}

func (x *EarthResponse_Frame) GetMag() *EarthResponse_Frame_Mag {
	if x != nil {
		return x.Mag
	}
	return nil
}

type EarthResponse_Frame_Geo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LatDeg        float64                `protobuf:"fixed64,1,opt,name=lat_deg,json=latDeg,proto3" json:"lat_deg,omitempty"`
	LonDeg        float64                `protobuf:"fixed64,2,opt,name=lon_deg,json=lonDeg,proto3" json:"lon_deg,omitempty"`
	AltKm         float64                `protobuf:"fixed64,3,opt,name=alt_km,json=altKm,proto3" json:"alt_km,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EarthResponse_Frame_Geo) Reset() {
	*x = EarthResponse_Frame_Geo{}
	mi := &file_Earth_simulation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EarthResponse_Frame_Geo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EarthResponse_Frame_Geo) ProtoMessage() {}

func (x *EarthResponse_Frame_Geo) ProtoReflect() protoreflect.Message {
	mi := &file_Earth_simulation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EarthResponse_Frame_Geo.ProtoReflect.Descriptor instead.
func (*EarthResponse_Frame_Geo) Descriptor() ([]byte, []int) {
	return file_Earth_simulation_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *EarthResponse_Frame_Geo) GetLatDeg() float64 {
	if x != nil {
		return x.LatDeg
	}
	return 0
}

func (x *EarthResponse_Frame_Geo) GetLonDeg() float64 {
	if x != nil {
		return x.LonDeg
	}
	return 0
}

func (x *EarthResponse_Frame_Geo) GetAltKm() float64 {
	if x != nil {
		return x.AltKm
	}
	return 0
}

type EarthResponse_Frame_Mag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XNT           float64                `protobuf:"fixed64,1,opt,name=x_nT,json=xNT,proto3" json:"x_nT,omitempty"`
	YNT           float64                `protobuf:"fixed64,2,opt,name=y_nT,json=yNT,proto3" json:"y_nT,omitempty"`
	ZNT           float64                `protobuf:"fixed64,3,opt,name=z_nT,json=zNT,proto3" json:"z_nT,omitempty"`
	FNT           float64                `protobuf:"fixed64,4,opt,name=f_nT,json=fNT,proto3" json:"f_nT,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EarthResponse_Frame_Mag) Reset() {
	*x = EarthResponse_Frame_Mag{}
	mi := &file_Earth_simulation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EarthResponse_Frame_Mag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EarthResponse_Frame_Mag) ProtoMessage() {}

func (x *EarthResponse_Frame_Mag) ProtoReflect() protoreflect.Message {
	mi := &file_Earth_simulation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EarthResponse_Frame_Mag.ProtoReflect.Descriptor instead.
func (*EarthResponse_Frame_Mag) Descriptor() ([]byte, []int) {
	return file_Earth_simulation_proto_rawDescGZIP(), []int{1, 0, 1}
}

func (x *EarthResponse_Frame_Mag) GetXNT() float64 {
	if x != nil {
		return x.XNT
	}
	return 0
}

func (x *EarthResponse_Frame_Mag) GetYNT() float64 {
	if x != nil {
		return x.YNT
	}
	return 0
}

func (x *EarthResponse_Frame_Mag) GetZNT() float64 {
	if x != nil {
		return x.ZNT
	}
	return 0
}

func (x *EarthResponse_Frame_Mag) GetFNT() float64 {
	if x != nil {
		return x.FNT
	}
	return 0
}

var File_Earth_simulation_proto protoreflect.FileDescriptor

const file_Earth_simulation_proto_rawDesc = "" +
	"\n" +
	"\x16Earth_simulation.proto\x12\x0fEarthSimulation\"\xf6\x01\n" +
	"\fEarthRequest\x129\n" +
	"\x05nodes\x18\x01 \x03(\v2#.EarthSimulation.EarthRequest.NodesR\x05nodes\x1a\xaa\x01\n" +
	"\x05Nodes\x12\x16\n" +
	"\at_rel_s\x18\x01 \x01(\x01R\x05tRelS\x129\n" +
	"\x03geo\x18\x02 \x01(\v2'.EarthSimulation.EarthRequest.Nodes.GeoR\x03geo\x1aN\n" +
	"\x03Geo\x12\x17\n" +
	"\alat_deg\x18\x01 \x01(\x01R\x06latDeg\x12\x17\n" +
	"\alon_deg\x18\x02 \x01(\x01R\x06lonDeg\x12\x15\n" +
	"\x06alt_km\x18\x03 \x01(\x01R\x05altKm\"\x8a\x03\n" +
	"\rEarthResponse\x12<\n" +
	"\x06frames\x18\x01 \x03(\v2$.EarthSimulation.EarthResponse.FrameR\x06frames\x1a\xba\x02\n" +
	"\x05Frame\x12\x16\n" +
	"\at_rel_s\x18\x01 \x01(\x01R\x05tRelS\x12:\n" +
	"\x03geo\x18\x02 \x01(\v2(.EarthSimulation.EarthResponse.Frame.GeoR\x03geo\x12:\n" +
	"\x03mag\x18\x03 \x01(\v2(.EarthSimulation.EarthResponse.Frame.MagR\x03mag\x1aN\n" +
	"\x03Geo\x12\x17\n" +
	"\alat_deg\x18\x01 \x01(\x01R\x06latDeg\x12\x17\n" +
	"\alon_deg\x18\x02 \x01(\x01R\x06lonDeg\x12\x15\n" +
	"\x06alt_km\x18\x03 \x01(\x01R\x05altKm\x1aQ\n" +
	"\x03Mag\x12\x11\n" +
	"\x04x_nT\x18\x01 \x01(\x01R\x03xNT\x12\x11\n" +
	"\x04y_nT\x18\x02 \x01(\x01R\x03yNT\x12\x11\n" +
	"\x04z_nT\x18\x03 \x01(\x01R\x03zNT\x12\x11\n" +
	"\x04f_nT\x18\x04 \x01(\x01R\x03fNT2h\n" +
	"\x16EarthSimulationService\x12N\n" +
	"\rSendEarthData\x12\x1d.EarthSimulation.EarthRequest\x1a\x1e.EarthSimulation.EarthResponseB+Z)github.com/Theossr/Helikos_test/api/protob\x06proto3"

var (
	file_Earth_simulation_proto_rawDescOnce sync.Once
	file_Earth_simulation_proto_rawDescData []byte
)

func file_Earth_simulation_proto_rawDescGZIP() []byte {
	file_Earth_simulation_proto_rawDescOnce.Do(func() {
		file_Earth_simulation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Earth_simulation_proto_rawDesc), len(file_Earth_simulation_proto_rawDesc)))
	})
	return file_Earth_simulation_proto_rawDescData
}

var file_Earth_simulation_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_Earth_simulation_proto_goTypes = []any{
	(*EarthRequest)(nil),            // 0: EarthSimulation.EarthRequest
	(*EarthResponse)(nil),           // 1: EarthSimulation.EarthResponse
	(*EarthRequest_Nodes)(nil),      // 2: EarthSimulation.EarthRequest.Nodes
	(*EarthRequest_Nodes_Geo)(nil),  // 3: EarthSimulation.EarthRequest.Nodes.Geo
	(*EarthResponse_Frame)(nil),     // 4: EarthSimulation.EarthResponse.Frame
	(*EarthResponse_Frame_Geo)(nil), // 5: EarthSimulation.EarthResponse.Frame.Geo
	(*EarthResponse_Frame_Mag)(nil), // 6: EarthSimulation.EarthResponse.Frame.Mag
}
var file_Earth_simulation_proto_depIdxs = []int32{
	2, // 0: EarthSimulation.EarthRequest.nodes:type_name -> EarthSimulation.EarthRequest.Nodes
	4, // 1: EarthSimulation.EarthResponse.frames:type_name -> EarthSimulation.EarthResponse.Frame
	3, // 2: EarthSimulation.EarthRequest.Nodes.geo:type_name -> EarthSimulation.EarthRequest.Nodes.Geo
	5, // 3: EarthSimulation.EarthResponse.Frame.geo:type_name -> EarthSimulation.EarthResponse.Frame.Geo
	6, // 4: EarthSimulation.EarthResponse.Frame.mag:type_name -> EarthSimulation.EarthResponse.Frame.Mag
	0, // 5: EarthSimulation.EarthSimulationService.SendEarthData:input_type -> EarthSimulation.EarthRequest
	1, // 6: EarthSimulation.EarthSimulationService.SendEarthData:output_type -> EarthSimulation.EarthResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_Earth_simulation_proto_init() }
func file_Earth_simulation_proto_init() {
	if File_Earth_simulation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Earth_simulation_proto_rawDesc), len(file_Earth_simulation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Earth_simulation_proto_goTypes,
		DependencyIndexes: file_Earth_simulation_proto_depIdxs,
		MessageInfos:      file_Earth_simulation_proto_msgTypes,
	}.Build()
	File_Earth_simulation_proto = out.File
	file_Earth_simulation_proto_goTypes = nil
	file_Earth_simulation_proto_depIdxs = nil
}
