// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: Earth_simulation.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EarthSimulationService_SendEarthData_FullMethodName = "/EarthSimulation.EarthSimulationService/SendEarthData"
)

// EarthSimulationServiceClient is the client API for EarthSimulationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EarthSimulationServiceClient interface {
	SendEarthData(ctx context.Context, in *EarthRequest, opts ...grpc.CallOption) (*EarthResponse, error)
}

type earthSimulationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEarthSimulationServiceClient(cc grpc.ClientConnInterface) EarthSimulationServiceClient {
	return &earthSimulationServiceClient{cc}
}

func (c *earthSimulationServiceClient) SendEarthData(ctx context.Context, in *EarthRequest, opts ...grpc.CallOption) (*EarthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EarthResponse)
	err := c.cc.Invoke(ctx, EarthSimulationService_SendEarthData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EarthSimulationServiceServer is the server API for EarthSimulationService service.
// All implementations must embed UnimplementedEarthSimulationServiceServer
// for forward compatibility.
type EarthSimulationServiceServer interface {
	SendEarthData(context.Context, *EarthRequest) (*EarthResponse, error)
	mustEmbedUnimplementedEarthSimulationServiceServer()
}

// UnimplementedEarthSimulationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEarthSimulationServiceServer struct{}

func (UnimplementedEarthSimulationServiceServer) SendEarthData(context.Context, *EarthRequest) (*EarthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEarthData not implemented")
}
func (UnimplementedEarthSimulationServiceServer) mustEmbedUnimplementedEarthSimulationServiceServer() {
}
func (UnimplementedEarthSimulationServiceServer) testEmbeddedByValue() {}

// UnsafeEarthSimulationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EarthSimulationServiceServer will
// result in compilation errors.
type UnsafeEarthSimulationServiceServer interface {
	mustEmbedUnimplementedEarthSimulationServiceServer()
}

func RegisterEarthSimulationServiceServer(s grpc.ServiceRegistrar, srv EarthSimulationServiceServer) {
	// If the following call pancis, it indicates UnimplementedEarthSimulationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EarthSimulationService_ServiceDesc, srv)
}

func _EarthSimulationService_SendEarthData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EarthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EarthSimulationServiceServer).SendEarthData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EarthSimulationService_SendEarthData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EarthSimulationServiceServer).SendEarthData(ctx, req.(*EarthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EarthSimulationService_ServiceDesc is the grpc.ServiceDesc for EarthSimulationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EarthSimulationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "EarthSimulation.EarthSimulationService",
	HandlerType: (*EarthSimulationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEarthData",
			Handler:    _EarthSimulationService_SendEarthData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Earth_simulation.proto",
}
