// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: satellite_Earth_simulation.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tle          *SimRequest_TLE `protobuf:"bytes,1,opt,name=tle,proto3" json:"tle,omitempty"`
	StartEpochMs uint64          `protobuf:"varint,2,opt,name=start_epoch_ms,json=startEpochMs,proto3" json:"start_epoch_ms,omitempty"`
	DurationS    float64         `protobuf:"fixed64,3,opt,name=duration_s,json=durationS,proto3" json:"duration_s,omitempty"`
	StepS        float64         `protobuf:"fixed64,4,opt,name=step_s,json=stepS,proto3" json:"step_s,omitempty"`
	HFailKm      float64         `protobuf:"fixed64,5,opt,name=h_fail_km,json=hFailKm,proto3" json:"h_fail_km,omitempty"`
}

func (x *SimRequest) Reset() {
	*x = SimRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_satellite_Earth_simulation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimRequest) ProtoMessage() {}

func (x *SimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_Earth_simulation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimRequest.ProtoReflect.Descriptor instead.
func (*SimRequest) Descriptor() ([]byte, []int) {
	return file_satellite_Earth_simulation_proto_rawDescGZIP(), []int{0}
}

func (x *SimRequest) GetTle() *SimRequest_TLE {
	if x != nil {
		return x.Tle
	}
	return nil
}

func (x *SimRequest) GetStartEpochMs() uint64 {
	if x != nil {
		return x.StartEpochMs
	}
	return 0
}

func (x *SimRequest) GetDurationS() float64 {
	if x != nil {
		return x.DurationS
	}
	return 0
}

func (x *SimRequest) GetStepS() float64 {
	if x != nil {
		return x.StepS
	}
	return 0
}

func (x *SimRequest) GetHFailKm() float64 {
	if x != nil {
		return x.HFailKm
	}
	return 0
}

type SimResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Frames []*SimResponse_Frame `protobuf:"bytes,1,rep,name=frames,proto3" json:"frames,omitempty"`
	Decay  *SimResponse_Decay   `protobuf:"bytes,2,opt,name=decay,proto3" json:"decay,omitempty"`
	Meta   *SimResponse_Meta    `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
}

func (x *SimResponse) Reset() {
	*x = SimResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_satellite_Earth_simulation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimResponse) ProtoMessage() {}

func (x *SimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_Earth_simulation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimResponse.ProtoReflect.Descriptor instead.
func (*SimResponse) Descriptor() ([]byte, []int) {
	return file_satellite_Earth_simulation_proto_rawDescGZIP(), []int{1}
}

func (x *SimResponse) GetFrames() []*SimResponse_Frame {
	if x != nil {
		return x.Frames
	}
	return nil
}

func (x *SimResponse) GetDecay() *SimResponse_Decay {
	if x != nil {
		return x.Decay
	}
	return nil
}

func (x *SimResponse) GetMeta() *SimResponse_Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// TLE
type SimRequest_TLE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Line1 string `protobuf:"bytes,2,opt,name=line1,proto3" json:"line1,omitempty"`
	Line2 string `protobuf:"bytes,3,opt,name=line2,proto3" json:"line2,omitempty"`
}

func (x *SimRequest_TLE) Reset() {
	*x = SimRequest_TLE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_satellite_Earth_simulation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimRequest_TLE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimRequest_TLE) ProtoMessage() {}

func (x *SimRequest_TLE) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_Earth_simulation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimRequest_TLE.ProtoReflect.Descriptor instead.
func (*SimRequest_TLE) Descriptor() ([]byte, []int) {
	return file_satellite_Earth_simulation_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SimRequest_TLE) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SimRequest_TLE) GetLine1() string {
	if x != nil {
		return x.Line1
	}
	return ""
}

func (x *SimRequest_TLE) GetLine2() string {
	if x != nil {
		return x.Line2
	}
	return ""
}

// Frames
type SimResponse_Frame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TRelS float64                `protobuf:"fixed64,1,opt,name=t_rel_s,json=tRelS,proto3" json:"t_rel_s,omitempty"`
	Geo   *SimResponse_Frame_Geo `protobuf:"bytes,2,opt,name=geo,proto3" json:"geo,omitempty"`
	Mag   *SimResponse_Frame_Mag `protobuf:"bytes,3,opt,name=mag,proto3" json:"mag,omitempty"`
}

func (x *SimResponse_Frame) Reset() {
	*x = SimResponse_Frame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_satellite_Earth_simulation_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimResponse_Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimResponse_Frame) ProtoMessage() {}

func (x *SimResponse_Frame) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_Earth_simulation_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimResponse_Frame.ProtoReflect.Descriptor instead.
func (*SimResponse_Frame) Descriptor() ([]byte, []int) {
	return file_satellite_Earth_simulation_proto_rawDescGZIP(), []int{1, 0}
}

func (x *SimResponse_Frame) GetTRelS() float64 {
	if x != nil {
		return x.TRelS
	}
	return 0
}

func (x *SimResponse_Frame) GetGeo() *SimResponse_Frame_Geo {
	if x != nil {
		return x.Geo
	}
	return nil
}

func (x *SimResponse_Frame) GetMag() *SimResponse_Frame_Mag {
	if x != nil {
		return x.Mag
	}
	return nil
}

// Decay
type SimResponse_Decay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ThresholdKm float64                        `protobuf:"fixed64,1,opt,name=threshold_km,json=thresholdKm,proto3" json:"threshold_km,omitempty"`
	TleForward  *SimResponse_Decay_TLEForward  `protobuf:"bytes,2,opt,name=tle_forward,json=tleForward,proto3" json:"tle_forward,omitempty"`
	PhysicsDrag *SimResponse_Decay_PhysicsDrag `protobuf:"bytes,3,opt,name=physics_drag,json=physicsDrag,proto3" json:"physics_drag,omitempty"`
}

func (x *SimResponse_Decay) Reset() {
	*x = SimResponse_Decay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_satellite_Earth_simulation_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimResponse_Decay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimResponse_Decay) ProtoMessage() {}

func (x *SimResponse_Decay) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_Earth_simulation_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimResponse_Decay.ProtoReflect.Descriptor instead.
func (*SimResponse_Decay) Descriptor() ([]byte, []int) {
	return file_satellite_Earth_simulation_proto_rawDescGZIP(), []int{1, 1}
}

func (x *SimResponse_Decay) GetThresholdKm() float64 {
	if x != nil {
		return x.ThresholdKm
	}
	return 0
}

func (x *SimResponse_Decay) GetTleForward() *SimResponse_Decay_TLEForward {
	if x != nil {
		return x.TleForward
	}
	return nil
}

func (x *SimResponse_Decay) GetPhysicsDrag() *SimResponse_Decay_PhysicsDrag {
	if x != nil {
		return x.PhysicsDrag
	}
	return nil
}

// Meta
type SimResponse_Meta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PointsGenerated     uint32 `protobuf:"varint,2,opt,name=points_generated,json=pointsGenerated,proto3" json:"points_generated,omitempty"`
	TleEpochUtc         string `protobuf:"bytes,4,opt,name=tle_epoch_utc,json=tleEpochUtc,proto3" json:"tle_epoch_utc,omitempty"`
	OutOfTleEpochWindow bool   `protobuf:"varint,5,opt,name=out_of_tle_epoch_window,json=outOfTleEpochWindow,proto3" json:"out_of_tle_epoch_window,omitempty"`
}

func (x *SimResponse_Meta) Reset() {
	*x = SimResponse_Meta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_satellite_Earth_simulation_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimResponse_Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimResponse_Meta) ProtoMessage() {}

func (x *SimResponse_Meta) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_Earth_simulation_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimResponse_Meta.ProtoReflect.Descriptor instead.
func (*SimResponse_Meta) Descriptor() ([]byte, []int) {
	return file_satellite_Earth_simulation_proto_rawDescGZIP(), []int{1, 2}
}

func (x *SimResponse_Meta) GetPointsGenerated() uint32 {
	if x != nil {
		return x.PointsGenerated
	}
	return 0
}

func (x *SimResponse_Meta) GetTleEpochUtc() string {
	if x != nil {
		return x.TleEpochUtc
	}
	return ""
}

func (x *SimResponse_Meta) GetOutOfTleEpochWindow() bool {
	if x != nil {
		return x.OutOfTleEpochWindow
	}
	return false
}

type SimResponse_Frame_Geo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LatDeg float64 `protobuf:"fixed64,1,opt,name=lat_deg,json=latDeg,proto3" json:"lat_deg,omitempty"`
	LonDeg float64 `protobuf:"fixed64,2,opt,name=lon_deg,json=lonDeg,proto3" json:"lon_deg,omitempty"`
	AltKm  float64 `protobuf:"fixed64,3,opt,name=alt_km,json=altKm,proto3" json:"alt_km,omitempty"`
}

func (x *SimResponse_Frame_Geo) Reset() {
	*x = SimResponse_Frame_Geo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_satellite_Earth_simulation_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimResponse_Frame_Geo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimResponse_Frame_Geo) ProtoMessage() {}

func (x *SimResponse_Frame_Geo) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_Earth_simulation_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimResponse_Frame_Geo.ProtoReflect.Descriptor instead.
func (*SimResponse_Frame_Geo) Descriptor() ([]byte, []int) {
	return file_satellite_Earth_simulation_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *SimResponse_Frame_Geo) GetLatDeg() float64 {
	if x != nil {
		return x.LatDeg
	}
	return 0
}

func (x *SimResponse_Frame_Geo) GetLonDeg() float64 {
	if x != nil {
		return x.LonDeg
	}
	return 0
}

func (x *SimResponse_Frame_Geo) GetAltKm() float64 {
	if x != nil {
		return x.AltKm
	}
	return 0
}

type SimResponse_Frame_Mag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	XNT float64 `protobuf:"fixed64,1,opt,name=x_nT,json=xNT,proto3" json:"x_nT,omitempty"`
	YNT float64 `protobuf:"fixed64,2,opt,name=y_nT,json=yNT,proto3" json:"y_nT,omitempty"`
	ZNT float64 `protobuf:"fixed64,3,opt,name=z_nT,json=zNT,proto3" json:"z_nT,omitempty"`
	FNT float64 `protobuf:"fixed64,4,opt,name=f_nT,json=fNT,proto3" json:"f_nT,omitempty"`
}

func (x *SimResponse_Frame_Mag) Reset() {
	*x = SimResponse_Frame_Mag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_satellite_Earth_simulation_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimResponse_Frame_Mag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimResponse_Frame_Mag) ProtoMessage() {}

func (x *SimResponse_Frame_Mag) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_Earth_simulation_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimResponse_Frame_Mag.ProtoReflect.Descriptor instead.
func (*SimResponse_Frame_Mag) Descriptor() ([]byte, []int) {
	return file_satellite_Earth_simulation_proto_rawDescGZIP(), []int{1, 0, 1}
}

func (x *SimResponse_Frame_Mag) GetXNT() float64 {
	if x != nil {
		return x.XNT
	}
	return 0
}

func (x *SimResponse_Frame_Mag) GetYNT() float64 {
	if x != nil {
		return x.YNT
	}
	return 0
}

func (x *SimResponse_Frame_Mag) GetZNT() float64 {
	if x != nil {
		return x.ZNT
	}
	return 0
}

func (x *SimResponse_Frame_Mag) GetFNT() float64 {
	if x != nil {
		return x.FNT
	}
	return 0
}

type SimResponse_Decay_TLEForward struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Crossed        bool    `protobuf:"varint,1,opt,name=crossed,proto3" json:"crossed,omitempty"`
	TimeUtc        string  `protobuf:"bytes,2,opt,name=time_utc,json=timeUtc,proto3" json:"time_utc,omitempty"`
	TimeFromStartS float64 `protobuf:"fixed64,3,opt,name=time_from_start_s,json=timeFromStartS,proto3" json:"time_from_start_s,omitempty"`
	UncertaintyS   float64 `protobuf:"fixed64,4,opt,name=uncertainty_s,json=uncertaintyS,proto3" json:"uncertainty_s,omitempty"`
}

func (x *SimResponse_Decay_TLEForward) Reset() {
	*x = SimResponse_Decay_TLEForward{}
	if protoimpl.UnsafeEnabled {
		mi := &file_satellite_Earth_simulation_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimResponse_Decay_TLEForward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimResponse_Decay_TLEForward) ProtoMessage() {}

func (x *SimResponse_Decay_TLEForward) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_Earth_simulation_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimResponse_Decay_TLEForward.ProtoReflect.Descriptor instead.
func (*SimResponse_Decay_TLEForward) Descriptor() ([]byte, []int) {
	return file_satellite_Earth_simulation_proto_rawDescGZIP(), []int{1, 1, 0}
}

func (x *SimResponse_Decay_TLEForward) GetCrossed() bool {
	if x != nil {
		return x.Crossed
	}
	return false
}

func (x *SimResponse_Decay_TLEForward) GetTimeUtc() string {
	if x != nil {
		return x.TimeUtc
	}
	return ""
}

func (x *SimResponse_Decay_TLEForward) GetTimeFromStartS() float64 {
	if x != nil {
		return x.TimeFromStartS
	}
	return 0
}

func (x *SimResponse_Decay_TLEForward) GetUncertaintyS() float64 {
	if x != nil {
		return x.UncertaintyS
	}
	return 0
}

type SimResponse_Decay_PhysicsDrag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Crossed        bool    `protobuf:"varint,1,opt,name=crossed,proto3" json:"crossed,omitempty"`
	TimeUtc        string  `protobuf:"bytes,2,opt,name=time_utc,json=timeUtc,proto3" json:"time_utc,omitempty"`
	TimeFromStartS float64 `protobuf:"fixed64,3,opt,name=time_from_start_s,json=timeFromStartS,proto3" json:"time_from_start_s,omitempty"`
	UncertaintyS   float64 `protobuf:"fixed64,4,opt,name=uncertainty_s,json=uncertaintyS,proto3" json:"uncertainty_s,omitempty"`
}

func (x *SimResponse_Decay_PhysicsDrag) Reset() {
	*x = SimResponse_Decay_PhysicsDrag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_satellite_Earth_simulation_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimResponse_Decay_PhysicsDrag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimResponse_Decay_PhysicsDrag) ProtoMessage() {}

func (x *SimResponse_Decay_PhysicsDrag) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_Earth_simulation_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimResponse_Decay_PhysicsDrag.ProtoReflect.Descriptor instead.
func (*SimResponse_Decay_PhysicsDrag) Descriptor() ([]byte, []int) {
	return file_satellite_Earth_simulation_proto_rawDescGZIP(), []int{1, 1, 1}
}

func (x *SimResponse_Decay_PhysicsDrag) GetCrossed() bool {
	if x != nil {
		return x.Crossed
	}
	return false
}

func (x *SimResponse_Decay_PhysicsDrag) GetTimeUtc() string {
	if x != nil {
		return x.TimeUtc
	}
	return ""
}

func (x *SimResponse_Decay_PhysicsDrag) GetTimeFromStartS() float64 {
	if x != nil {
		return x.TimeFromStartS
	}
	return 0
}

func (x *SimResponse_Decay_PhysicsDrag) GetUncertaintyS() float64 {
	if x != nil {
		return x.UncertaintyS
	}
	return 0
}

var File_satellite_Earth_simulation_proto protoreflect.FileDescriptor

var file_satellite_Earth_simulation_proto_rawDesc = []byte{
	0x0a, 0x20, 0x73, 0x61, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x74, 0x65, 0x5f, 0x45, 0x61, 0x72, 0x74,
	0x68, 0x5f, 0x73, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x18, 0x53, 0x61, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x74, 0x65, 0x45, 0x61, 0x72,
	0x74, 0x68, 0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x89, 0x02, 0x0a,
	0x0a, 0x53, 0x69, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x03, 0x74,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x53, 0x61, 0x74, 0x65, 0x6c,
	0x6c, 0x69, 0x74, 0x65, 0x45, 0x61, 0x72, 0x74, 0x68, 0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x69, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x54,
	0x4c, 0x45, 0x52, 0x03, 0x74, 0x6c, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x5f, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x5f, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0c, 0x73, 0x74, 0x61, 0x72, 0x74, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x4d, 0x73, 0x12, 0x1d, 0x0a,
	0x0a, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x09, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x12, 0x15, 0x0a, 0x06,
	0x73, 0x74, 0x65, 0x70, 0x5f, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x74,
	0x65, 0x70, 0x53, 0x12, 0x1a, 0x0a, 0x09, 0x68, 0x5f, 0x66, 0x61, 0x69, 0x6c, 0x5f, 0x6b, 0x6d,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x68, 0x46, 0x61, 0x69, 0x6c, 0x4b, 0x6d, 0x1a,
	0x47, 0x0a, 0x03, 0x54, 0x4c, 0x45, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x69, 0x6e, 0x65, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x69, 0x6e,
	0x65, 0x31, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x32, 0x22, 0xb9, 0x09, 0x0a, 0x0b, 0x53, 0x69, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x06, 0x66, 0x72, 0x61, 0x6d,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x53, 0x61, 0x74, 0x65, 0x6c,
	0x6c, 0x69, 0x74, 0x65, 0x45, 0x61, 0x72, 0x74, 0x68, 0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x69, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x46, 0x72, 0x61, 0x6d, 0x65, 0x52, 0x06, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x41, 0x0a,
	0x05, 0x64, 0x65, 0x63, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x53,
	0x61, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x74, 0x65, 0x45, 0x61, 0x72, 0x74, 0x68, 0x53, 0x69, 0x6d,
	0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x69, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x44, 0x65, 0x63, 0x61, 0x79, 0x52, 0x05, 0x64, 0x65, 0x63, 0x61, 0x79,
	0x12, 0x3e, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a,
	0x2e, 0x53, 0x61, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x74, 0x65, 0x45, 0x61, 0x72, 0x74, 0x68, 0x53,
	0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x69, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61,
	0x1a, 0xc8, 0x02, 0x0a, 0x05, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x07, 0x74, 0x5f,
	0x72, 0x65, 0x6c, 0x5f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x74, 0x52, 0x65,
	0x6c, 0x53, 0x12, 0x41, 0x0a, 0x03, 0x67, 0x65, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2f, 0x2e, 0x53, 0x61, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x74, 0x65, 0x45, 0x61, 0x72, 0x74, 0x68,
	0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x69, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x47, 0x65, 0x6f,
	0x52, 0x03, 0x67, 0x65, 0x6f, 0x12, 0x41, 0x0a, 0x03, 0x6d, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x53, 0x61, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x74, 0x65, 0x45, 0x61,
	0x72, 0x74, 0x68, 0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x69,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x2e,
	0x4d, 0x61, 0x67, 0x52, 0x03, 0x6d, 0x61, 0x67, 0x1a, 0x4e, 0x0a, 0x03, 0x47, 0x65, 0x6f, 0x12,
	0x17, 0x0a, 0x07, 0x6c, 0x61, 0x74, 0x5f, 0x64, 0x65, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x06, 0x6c, 0x61, 0x74, 0x44, 0x65, 0x67, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x6f, 0x6e, 0x5f,
	0x64, 0x65, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x6c, 0x6f, 0x6e, 0x44, 0x65,
	0x67, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x6c, 0x74, 0x5f, 0x6b, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x05, 0x61, 0x6c, 0x74, 0x4b, 0x6d, 0x1a, 0x51, 0x0a, 0x03, 0x4d, 0x61, 0x67, 0x12,
	0x11, 0x0a, 0x04, 0x78, 0x5f, 0x6e, 0x54, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x78,
	0x4e, 0x54, 0x12, 0x11, 0x0a, 0x04, 0x79, 0x5f, 0x6e, 0x54, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x03, 0x79, 0x4e, 0x54, 0x12, 0x11, 0x0a, 0x04, 0x7a, 0x5f, 0x6e, 0x54, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x03, 0x7a, 0x4e, 0x54, 0x12, 0x11, 0x0a, 0x04, 0x66, 0x5f, 0x6e, 0x54,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x66, 0x4e, 0x54, 0x1a, 0x88, 0x04, 0x0a, 0x05,
	0x44, 0x65, 0x63, 0x61, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f,
	0x6c, 0x64, 0x5f, 0x6b, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x74, 0x68, 0x72,
	0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x4b, 0x6d, 0x12, 0x57, 0x0a, 0x0b, 0x74, 0x6c, 0x65, 0x5f,
	0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x36, 0x2e,
	0x53, 0x61, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x74, 0x65, 0x45, 0x61, 0x72, 0x74, 0x68, 0x53, 0x69,
	0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x69, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x65, 0x63, 0x61, 0x79, 0x2e, 0x54, 0x4c, 0x45, 0x46, 0x6f,
	0x72, 0x77, 0x61, 0x72, 0x64, 0x52, 0x0a, 0x74, 0x6c, 0x65, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72,
	0x64, 0x12, 0x5a, 0x0a, 0x0c, 0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x73, 0x5f, 0x64, 0x72, 0x61,
	0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x53, 0x61, 0x74, 0x65, 0x6c, 0x6c,
	0x69, 0x74, 0x65, 0x45, 0x61, 0x72, 0x74, 0x68, 0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x53, 0x69, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44,
	0x65, 0x63, 0x61, 0x79, 0x2e, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x73, 0x44, 0x72, 0x61, 0x67,
	0x52, 0x0b, 0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x73, 0x44, 0x72, 0x61, 0x67, 0x1a, 0x91, 0x01,
	0x0a, 0x0a, 0x54, 0x4c, 0x45, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x72, 0x6f, 0x73, 0x73, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63,
	0x72, 0x6f, 0x73, 0x73, 0x65, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x75,
	0x74, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x55, 0x74,
	0x63, 0x12, 0x29, 0x0a, 0x11, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x5f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0e, 0x74, 0x69,
	0x6d, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x12, 0x23, 0x0a, 0x0d,
	0x75, 0x6e, 0x63, 0x65, 0x72, 0x74, 0x61, 0x69, 0x6e, 0x74, 0x79, 0x5f, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x0c, 0x75, 0x6e, 0x63, 0x65, 0x72, 0x74, 0x61, 0x69, 0x6e, 0x74, 0x79,
	0x53, 0x1a, 0x92, 0x01, 0x0a, 0x0b, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x73, 0x44, 0x72, 0x61,
	0x67, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x6f, 0x73, 0x73, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x63, 0x72, 0x6f, 0x73, 0x73, 0x65, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x74,
	0x69, 0x6d, 0x65, 0x5f, 0x75, 0x74, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74,
	0x69, 0x6d, 0x65, 0x55, 0x74, 0x63, 0x12, 0x29, 0x0a, 0x11, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x66,
	0x72, 0x6f, 0x6d, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x53, 0x12, 0x23, 0x0a, 0x0d, 0x75, 0x6e, 0x63, 0x65, 0x72, 0x74, 0x61, 0x69, 0x6e, 0x74, 0x79,
	0x5f, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x75, 0x6e, 0x63, 0x65, 0x72, 0x74,
	0x61, 0x69, 0x6e, 0x74, 0x79, 0x53, 0x1a, 0x8b, 0x01, 0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x12,
	0x29, 0x0a, 0x10, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x73, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x74, 0x6c,
	0x65, 0x5f, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x5f, 0x75, 0x74, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x74, 0x6c, 0x65, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x55, 0x74, 0x63, 0x12, 0x34,
	0x0a, 0x17, 0x6f, 0x75, 0x74, 0x5f, 0x6f, 0x66, 0x5f, 0x74, 0x6c, 0x65, 0x5f, 0x65, 0x70, 0x6f,
	0x63, 0x68, 0x5f, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x13, 0x6f, 0x75, 0x74, 0x4f, 0x66, 0x54, 0x6c, 0x65, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x57, 0x69,
	0x6e, 0x64, 0x6f, 0x77, 0x32, 0x7f, 0x0a, 0x1f, 0x53, 0x61, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x74,
	0x65, 0x45, 0x61, 0x72, 0x74, 0x68, 0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5c, 0x0a, 0x0d, 0x52, 0x75, 0x6e, 0x53, 0x69,
	0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x2e, 0x53, 0x61, 0x74, 0x65, 0x6c,
	0x6c, 0x69, 0x74, 0x65, 0x45, 0x61, 0x72, 0x74, 0x68, 0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x69, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25,
	0x2e, 0x53, 0x61, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x74, 0x65, 0x45, 0x61, 0x72, 0x74, 0x68, 0x53,
	0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x69, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x54, 0x68, 0x65, 0x6f, 0x73, 0x73, 0x72, 0x2f, 0x48, 0x65, 0x6c, 0x69,
	0x6b, 0x6f, 0x73, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_satellite_Earth_simulation_proto_rawDescOnce sync.Once
	file_satellite_Earth_simulation_proto_rawDescData = file_satellite_Earth_simulation_proto_rawDesc
)

func file_satellite_Earth_simulation_proto_rawDescGZIP() []byte {
	file_satellite_Earth_simulation_proto_rawDescOnce.Do(func() {
		file_satellite_Earth_simulation_proto_rawDescData = protoimpl.X.CompressGZIP(file_satellite_Earth_simulation_proto_rawDescData)
	})
	return file_satellite_Earth_simulation_proto_rawDescData
}

var file_satellite_Earth_simulation_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_satellite_Earth_simulation_proto_goTypes = []interface{}{
	(*SimRequest)(nil),                    // 0: SatelliteEarthSimulation.SimRequest
	(*SimResponse)(nil),                   // 1: SatelliteEarthSimulation.SimResponse
	(*SimRequest_TLE)(nil),                // 2: SatelliteEarthSimulation.SimRequest.TLE
	(*SimResponse_Frame)(nil),             // 3: SatelliteEarthSimulation.SimResponse.Frame
	(*SimResponse_Decay)(nil),             // 4: SatelliteEarthSimulation.SimResponse.Decay
	(*SimResponse_Meta)(nil),              // 5: SatelliteEarthSimulation.SimResponse.Meta
	(*SimResponse_Frame_Geo)(nil),         // 6: SatelliteEarthSimulation.SimResponse.Frame.Geo
	(*SimResponse_Frame_Mag)(nil),         // 7: SatelliteEarthSimulation.SimResponse.Frame.Mag
	(*SimResponse_Decay_TLEForward)(nil),  // 8: SatelliteEarthSimulation.SimResponse.Decay.TLEForward
	(*SimResponse_Decay_PhysicsDrag)(nil), // 9: SatelliteEarthSimulation.SimResponse.Decay.PhysicsDrag
}
var file_satellite_Earth_simulation_proto_depIdxs = []int32{
	2, // 0: SatelliteEarthSimulation.SimRequest.tle:type_name -> SatelliteEarthSimulation.SimRequest.TLE
	3, // 1: SatelliteEarthSimulation.SimResponse.frames:type_name -> SatelliteEarthSimulation.SimResponse.Frame
	4, // 2: SatelliteEarthSimulation.SimResponse.decay:type_name -> SatelliteEarthSimulation.SimResponse.Decay
	5, // 3: SatelliteEarthSimulation.SimResponse.meta:type_name -> SatelliteEarthSimulation.SimResponse.Meta
	6, // 4: SatelliteEarthSimulation.SimResponse.Frame.geo:type_name -> SatelliteEarthSimulation.SimResponse.Frame.Geo
	7, // 5: SatelliteEarthSimulation.SimResponse.Frame.mag:type_name -> SatelliteEarthSimulation.SimResponse.Frame.Mag
	8, // 6: SatelliteEarthSimulation.SimResponse.Decay.tle_forward:type_name -> SatelliteEarthSimulation.SimResponse.Decay.TLEForward
	9, // 7: SatelliteEarthSimulation.SimResponse.Decay.physics_drag:type_name -> SatelliteEarthSimulation.SimResponse.Decay.PhysicsDrag
	0, // 8: SatelliteEarthSimulation.SatelliteEarthSimulationService.RunSimulation:input_type -> SatelliteEarthSimulation.SimRequest
	1, // 9: SatelliteEarthSimulation.SatelliteEarthSimulationService.RunSimulation:output_type -> SatelliteEarthSimulation.SimResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_satellite_Earth_simulation_proto_init() }
func file_satellite_Earth_simulation_proto_init() {
	if File_satellite_Earth_simulation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_satellite_Earth_simulation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_satellite_Earth_simulation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_satellite_Earth_simulation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimRequest_TLE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_satellite_Earth_simulation_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimResponse_Frame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_satellite_Earth_simulation_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimResponse_Decay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_satellite_Earth_simulation_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimResponse_Meta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_satellite_Earth_simulation_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimResponse_Frame_Geo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_satellite_Earth_simulation_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimResponse_Frame_Mag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_satellite_Earth_simulation_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimResponse_Decay_TLEForward); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_satellite_Earth_simulation_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimResponse_Decay_PhysicsDrag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_satellite_Earth_simulation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_satellite_Earth_simulation_proto_goTypes,
		DependencyIndexes: file_satellite_Earth_simulation_proto_depIdxs,
		MessageInfos:      file_satellite_Earth_simulation_proto_msgTypes,
	}.Build()
	File_satellite_Earth_simulation_proto = out.File
	file_satellite_Earth_simulation_proto_rawDesc = nil
	file_satellite_Earth_simulation_proto_goTypes = nil
	file_satellite_Earth_simulation_proto_depIdxs = nil
}
