// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: satellite_Earth_simulation.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tle           *SimRequest_TLE        `protobuf:"bytes,1,opt,name=tle,proto3" json:"tle,omitempty"`
	StartEpochMs  uint64                 `protobuf:"varint,2,opt,name=start_epoch_ms,json=startEpochMs,proto3" json:"start_epoch_ms,omitempty"`
	DurationS     float64                `protobuf:"fixed64,3,opt,name=duration_s,json=durationS,proto3" json:"duration_s,omitempty"`
	StepS         float64                `protobuf:"fixed64,4,opt,name=step_s,json=stepS,proto3" json:"step_s,omitempty"`
	HFailKm       float64                `protobuf:"fixed64,5,opt,name=h_fail_km,json=hFailKm,proto3" json:"h_fail_km,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimRequest) Reset() {
	*x = SimRequest{}
	mi := &file_satellite_Earth_simulation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimRequest) ProtoMessage() {}

func (x *SimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_Earth_simulation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimRequest.ProtoReflect.Descriptor instead.
func (*SimRequest) Descriptor() ([]byte, []int) {
	return file_satellite_Earth_simulation_proto_rawDescGZIP(), []int{0}
}

func (x *SimRequest) GetTle() *SimRequest_TLE {
	if x != nil {
		return x.Tle
	}
	return nil
}

func (x *SimRequest) GetStartEpochMs() uint64 {
	if x != nil {
		return x.StartEpochMs
	}
	return 0
}

func (x *SimRequest) GetDurationS() float64 {
	if x != nil {
		return x.DurationS
	}
	return 0
}

func (x *SimRequest) GetStepS() float64 {
	if x != nil {
		return x.StepS
	}
	return 0
}

func (x *SimRequest) GetHFailKm() float64 {
	if x != nil {
		return x.HFailKm
	}
	return 0
}

type SimResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frames        []*SimResponse_Frame   `protobuf:"bytes,1,rep,name=frames,proto3" json:"frames,omitempty"`
	Decay         *SimResponse_Decay     `protobuf:"bytes,2,opt,name=decay,proto3" json:"decay,omitempty"`
	Meta          *SimResponse_Meta      `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimResponse) Reset() {
	*x = SimResponse{}
	mi := &file_satellite_Earth_simulation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimResponse) ProtoMessage() {}

func (x *SimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_Earth_simulation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimResponse.ProtoReflect.Descriptor instead.
func (*SimResponse) Descriptor() ([]byte, []int) {
	return file_satellite_Earth_simulation_proto_rawDescGZIP(), []int{1}
}

func (x *SimResponse) GetFrames() []*SimResponse_Frame {
	if x != nil {
		return x.Frames
	}
	return nil
}

func (x *SimResponse) GetDecay() *SimResponse_Decay {
	if x != nil {
		return x.Decay
	}
	return nil
}

func (x *SimResponse) GetMeta() *SimResponse_Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// TLE
type SimRequest_TLE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Line1         string                 `protobuf:"bytes,2,opt,name=line1,proto3" json:"line1,omitempty"`
	Line2         string                 `protobuf:"bytes,3,opt,name=line2,proto3" json:"line2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimRequest_TLE) Reset() {
	*x = SimRequest_TLE{}
	mi := &file_satellite_Earth_simulation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimRequest_TLE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimRequest_TLE) ProtoMessage() {}

func (x *SimRequest_TLE) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_Earth_simulation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimRequest_TLE.ProtoReflect.Descriptor instead.
func (*SimRequest_TLE) Descriptor() ([]byte, []int) {
	return file_satellite_Earth_simulation_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SimRequest_TLE) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SimRequest_TLE) GetLine1() string {
	if x != nil {
		return x.Line1
	}
	return ""
}

func (x *SimRequest_TLE) GetLine2() string {
	if x != nil {
		return x.Line2
	}
	return ""
}

// Frames
type SimResponse_Frame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TRelS         float64                `protobuf:"fixed64,1,opt,name=t_rel_s,json=tRelS,proto3" json:"t_rel_s,omitempty"`
	Geo           *SimResponse_Frame_Geo `protobuf:"bytes,2,opt,name=geo,proto3" json:"geo,omitempty"`
	Mag           *SimResponse_Frame_Mag `protobuf:"bytes,3,opt,name=mag,proto3" json:"mag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimResponse_Frame) Reset() {
	*x = SimResponse_Frame{}
	mi := &file_satellite_Earth_simulation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimResponse_Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimResponse_Frame) ProtoMessage() {}

func (x *SimResponse_Frame) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_Earth_simulation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimResponse_Frame.ProtoReflect.Descriptor instead.
func (*SimResponse_Frame) Descriptor() ([]byte, []int) {
	return file_satellite_Earth_simulation_proto_rawDescGZIP(), []int{1, 0}
}

func (x *SimResponse_Frame) GetTRelS() float64 {
	if x != nil {
		return x.TRelS
	}
	return 0
}

func (x *SimResponse_Frame) GetGeo() *SimResponse_Frame_Geo {
	if x != nil {
		return x.Geo
	}
	return nil
}

func (x *SimResponse_Frame) GetMag() *SimResponse_Frame_Mag {
	if x != nil {
		return x.Mag
	}
	return nil
}

// Decay
type SimResponse_Decay struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	ThresholdKm   float64                        `protobuf:"fixed64,1,opt,name=threshold_km,json=thresholdKm,proto3" json:"threshold_km,omitempty"`
	TleForward    *SimResponse_Decay_TLEForward  `protobuf:"bytes,2,opt,name=tle_forward,json=tleForward,proto3" json:"tle_forward,omitempty"`
	PhysicsDrag   *SimResponse_Decay_PhysicsDrag `protobuf:"bytes,3,opt,name=physics_drag,json=physicsDrag,proto3" json:"physics_drag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimResponse_Decay) Reset() {
	*x = SimResponse_Decay{}
	mi := &file_satellite_Earth_simulation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimResponse_Decay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimResponse_Decay) ProtoMessage() {}

func (x *SimResponse_Decay) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_Earth_simulation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimResponse_Decay.ProtoReflect.Descriptor instead.
func (*SimResponse_Decay) Descriptor() ([]byte, []int) {
	return file_satellite_Earth_simulation_proto_rawDescGZIP(), []int{1, 1}
}

func (x *SimResponse_Decay) GetThresholdKm() float64 {
	if x != nil {
		return x.ThresholdKm
	}
	return 0
}

func (x *SimResponse_Decay) GetTleForward() *SimResponse_Decay_TLEForward {
	if x != nil {
		return x.TleForward
	}
	return nil
}

func (x *SimResponse_Decay) GetPhysicsDrag() *SimResponse_Decay_PhysicsDrag {
	if x != nil {
		return x.PhysicsDrag
	}
	return nil
}

// Meta
type SimResponse_Meta struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PointsReturned      uint32                 `protobuf:"varint,1,opt,name=points_returned,json=pointsReturned,proto3" json:"points_returned,omitempty"`
	PointsGenerated     uint32                 `protobuf:"varint,2,opt,name=points_generated,json=pointsGenerated,proto3" json:"points_generated,omitempty"`
	SkippedFrames       uint32                 `protobuf:"varint,3,opt,name=skipped_frames,json=skippedFrames,proto3" json:"skipped_frames,omitempty"`
	TleEpochUtc         string                 `protobuf:"bytes,4,opt,name=tle_epoch_utc,json=tleEpochUtc,proto3" json:"tle_epoch_utc,omitempty"`
	OutOfTleEpochWindow bool                   `protobuf:"varint,5,opt,name=out_of_tle_epoch_window,json=outOfTleEpochWindow,proto3" json:"out_of_tle_epoch_window,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SimResponse_Meta) Reset() {
	*x = SimResponse_Meta{}
	mi := &file_satellite_Earth_simulation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimResponse_Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimResponse_Meta) ProtoMessage() {}

func (x *SimResponse_Meta) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_Earth_simulation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimResponse_Meta.ProtoReflect.Descriptor instead.
func (*SimResponse_Meta) Descriptor() ([]byte, []int) {
	return file_satellite_Earth_simulation_proto_rawDescGZIP(), []int{1, 2}
}

func (x *SimResponse_Meta) GetPointsReturned() uint32 {
	if x != nil {
		return x.PointsReturned
	}
	return 0
}

func (x *SimResponse_Meta) GetPointsGenerated() uint32 {
	if x != nil {
		return x.PointsGenerated
	}
	return 0
}

func (x *SimResponse_Meta) GetSkippedFrames() uint32 {
	if x != nil {
		return x.SkippedFrames
	}
	return 0
}

func (x *SimResponse_Meta) GetTleEpochUtc() string {
	if x != nil {
		return x.TleEpochUtc
	}
	return ""
}

func (x *SimResponse_Meta) GetOutOfTleEpochWindow() bool {
	if x != nil {
		return x.OutOfTleEpochWindow
	}
	return false
}

type SimResponse_Frame_Geo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LatDeg        float64                `protobuf:"fixed64,1,opt,name=lat_deg,json=latDeg,proto3" json:"lat_deg,omitempty"`
	LonDeg        float64                `protobuf:"fixed64,2,opt,name=lon_deg,json=lonDeg,proto3" json:"lon_deg,omitempty"`
	AltKm         float64                `protobuf:"fixed64,3,opt,name=alt_km,json=altKm,proto3" json:"alt_km,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimResponse_Frame_Geo) Reset() {
	*x = SimResponse_Frame_Geo{}
	mi := &file_satellite_Earth_simulation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimResponse_Frame_Geo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimResponse_Frame_Geo) ProtoMessage() {}

func (x *SimResponse_Frame_Geo) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_Earth_simulation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimResponse_Frame_Geo.ProtoReflect.Descriptor instead.
func (*SimResponse_Frame_Geo) Descriptor() ([]byte, []int) {
	return file_satellite_Earth_simulation_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *SimResponse_Frame_Geo) GetLatDeg() float64 {
	if x != nil {
		return x.LatDeg
	}
	return 0
}

func (x *SimResponse_Frame_Geo) GetLonDeg() float64 {
	if x != nil {
		return x.LonDeg
	}
	return 0
}

func (x *SimResponse_Frame_Geo) GetAltKm() float64 {
	if x != nil {
		return x.AltKm
	}
	return 0
}

type SimResponse_Frame_Mag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XNT           float64                `protobuf:"fixed64,1,opt,name=x_nT,json=xNT,proto3" json:"x_nT,omitempty"`
	YNT           float64                `protobuf:"fixed64,2,opt,name=y_nT,json=yNT,proto3" json:"y_nT,omitempty"`
	ZNT           float64                `protobuf:"fixed64,3,opt,name=z_nT,json=zNT,proto3" json:"z_nT,omitempty"`
	FNT           float64                `protobuf:"fixed64,4,opt,name=f_nT,json=fNT,proto3" json:"f_nT,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimResponse_Frame_Mag) Reset() {
	*x = SimResponse_Frame_Mag{}
	mi := &file_satellite_Earth_simulation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimResponse_Frame_Mag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimResponse_Frame_Mag) ProtoMessage() {}

func (x *SimResponse_Frame_Mag) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_Earth_simulation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimResponse_Frame_Mag.ProtoReflect.Descriptor instead.
func (*SimResponse_Frame_Mag) Descriptor() ([]byte, []int) {
	return file_satellite_Earth_simulation_proto_rawDescGZIP(), []int{1, 0, 1}
}

func (x *SimResponse_Frame_Mag) GetXNT() float64 {
	if x != nil {
		return x.XNT
	}
	return 0
}

func (x *SimResponse_Frame_Mag) GetYNT() float64 {
	if x != nil {
		return x.YNT
	}
	return 0
}

func (x *SimResponse_Frame_Mag) GetZNT() float64 {
	if x != nil {
		return x.ZNT
	}
	return 0
}

func (x *SimResponse_Frame_Mag) GetFNT() float64 {
	if x != nil {
		return x.FNT
	}
	return 0
}

type SimResponse_Decay_TLEForward struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Crossed        bool                   `protobuf:"varint,1,opt,name=crossed,proto3" json:"crossed,omitempty"`
	TimeUtc        string                 `protobuf:"bytes,2,opt,name=time_utc,json=timeUtc,proto3" json:"time_utc,omitempty"`
	TimeFromStartS float64                `protobuf:"fixed64,3,opt,name=time_from_start_s,json=timeFromStartS,proto3" json:"time_from_start_s,omitempty"`
	UncertaintyS   float64                `protobuf:"fixed64,4,opt,name=uncertainty_s,json=uncertaintyS,proto3" json:"uncertainty_s,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SimResponse_Decay_TLEForward) Reset() {
	*x = SimResponse_Decay_TLEForward{}
	mi := &file_satellite_Earth_simulation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimResponse_Decay_TLEForward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimResponse_Decay_TLEForward) ProtoMessage() {}

func (x *SimResponse_Decay_TLEForward) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_Earth_simulation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimResponse_Decay_TLEForward.ProtoReflect.Descriptor instead.
func (*SimResponse_Decay_TLEForward) Descriptor() ([]byte, []int) {
	return file_satellite_Earth_simulation_proto_rawDescGZIP(), []int{1, 1, 0}
}

func (x *SimResponse_Decay_TLEForward) GetCrossed() bool {
	if x != nil {
		return x.Crossed
	}
	return false
}

func (x *SimResponse_Decay_TLEForward) GetTimeUtc() string {
	if x != nil {
		return x.TimeUtc
	}
	return ""
}

func (x *SimResponse_Decay_TLEForward) GetTimeFromStartS() float64 {
	if x != nil {
		return x.TimeFromStartS
	}
	return 0
}

func (x *SimResponse_Decay_TLEForward) GetUncertaintyS() float64 {
	if x != nil {
		return x.UncertaintyS
	}
	return 0
}

type SimResponse_Decay_PhysicsDrag struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Crossed        bool                   `protobuf:"varint,1,opt,name=crossed,proto3" json:"crossed,omitempty"`
	TimeUtc        string                 `protobuf:"bytes,2,opt,name=time_utc,json=timeUtc,proto3" json:"time_utc,omitempty"`
	TimeFromStartS float64                `protobuf:"fixed64,3,opt,name=time_from_start_s,json=timeFromStartS,proto3" json:"time_from_start_s,omitempty"`
	UncertaintyS   float64                `protobuf:"fixed64,4,opt,name=uncertainty_s,json=uncertaintyS,proto3" json:"uncertainty_s,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SimResponse_Decay_PhysicsDrag) Reset() {
	*x = SimResponse_Decay_PhysicsDrag{}
	mi := &file_satellite_Earth_simulation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimResponse_Decay_PhysicsDrag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimResponse_Decay_PhysicsDrag) ProtoMessage() {}

func (x *SimResponse_Decay_PhysicsDrag) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_Earth_simulation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimResponse_Decay_PhysicsDrag.ProtoReflect.Descriptor instead.
func (*SimResponse_Decay_PhysicsDrag) Descriptor() ([]byte, []int) {
	return file_satellite_Earth_simulation_proto_rawDescGZIP(), []int{1, 1, 1}
}

func (x *SimResponse_Decay_PhysicsDrag) GetCrossed() bool {
	if x != nil {
		return x.Crossed
	}
	return false
}

func (x *SimResponse_Decay_PhysicsDrag) GetTimeUtc() string {
	if x != nil {
		return x.TimeUtc
	}
	return ""
}

func (x *SimResponse_Decay_PhysicsDrag) GetTimeFromStartS() float64 {
	if x != nil {
		return x.TimeFromStartS
	}
	return 0
}

func (x *SimResponse_Decay_PhysicsDrag) GetUncertaintyS() float64 {
	if x != nil {
		return x.UncertaintyS
	}
	return 0
}

var File_satellite_Earth_simulation_proto protoreflect.FileDescriptor

const file_satellite_Earth_simulation_proto_rawDesc = "" +
	"\n" +
	" satellite_Earth_simulation.proto\x12\x18SatelliteEarthSimulation\"\x89\x02\n" +
	"\n" +
	"SimRequest\x12:\n" +
	"\x03tle\x18\x01 \x01(\v2(.SatelliteEarthSimulation.SimRequest.TLER\x03tle\x12$\n" +
	"\x0estart_epoch_ms\x18\x02 \x01(\x04R\fstartEpochMs\x12\x1d\n" +
	"\n" +
	"duration_s\x18\x03 \x01(\x01R\tdurationS\x12\x15\n" +
	"\x06step_s\x18\x04 \x01(\x01R\x05stepS\x12\x1a\n" +
	"\th_fail_km\x18\x05 \x01(\x01R\ahFailKm\x1aG\n" +
	"\x03TLE\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05line1\x18\x02 \x01(\tR\x05line1\x12\x14\n" +
	"\x05line2\x18\x03 \x01(\tR\x05line2\"\x89\n" +
	"\n" +
	"\vSimResponse\x12C\n" +
	"\x06frames\x18\x01 \x03(\v2+.SatelliteEarthSimulation.SimResponse.FrameR\x06frames\x12A\n" +
	"\x05decay\x18\x02 \x01(\v2+.SatelliteEarthSimulation.SimResponse.DecayR\x05decay\x12>\n" +
	"\x04meta\x18\x03 \x01(\v2*.SatelliteEarthSimulation.SimResponse.MetaR\x04meta\x1a\xc8\x02\n" +
	"\x05Frame\x12\x16\n" +
	"\at_rel_s\x18\x01 \x01(\x01R\x05tRelS\x12A\n" +
	"\x03geo\x18\x02 \x01(\v2/.SatelliteEarthSimulation.SimResponse.Frame.GeoR\x03geo\x12A\n" +
	"\x03mag\x18\x03 \x01(\v2/.SatelliteEarthSimulation.SimResponse.Frame.MagR\x03mag\x1aN\n" +
	"\x03Geo\x12\x17\n" +
	"\alat_deg\x18\x01 \x01(\x01R\x06latDeg\x12\x17\n" +
	"\alon_deg\x18\x02 \x01(\x01R\x06lonDeg\x12\x15\n" +
	"\x06alt_km\x18\x03 \x01(\x01R\x05altKm\x1aQ\n" +
	"\x03Mag\x12\x11\n" +
	"\x04x_nT\x18\x01 \x01(\x01R\x03xNT\x12\x11\n" +
	"\x04y_nT\x18\x02 \x01(\x01R\x03yNT\x12\x11\n" +
	"\x04z_nT\x18\x03 \x01(\x01R\x03zNT\x12\x11\n" +
	"\x04f_nT\x18\x04 \x01(\x01R\x03fNT\x1a\x88\x04\n" +
	"\x05Decay\x12!\n" +
	"\fthreshold_km\x18\x01 \x01(\x01R\vthresholdKm\x12W\n" +
	"\vtle_forward\x18\x02 \x01(\v26.SatelliteEarthSimulation.SimResponse.Decay.TLEForwardR\n" +
	"tleForward\x12Z\n" +
	"\fphysics_drag\x18\x03 \x01(\v27.SatelliteEarthSimulation.SimResponse.Decay.PhysicsDragR\vphysicsDrag\x1a\x91\x01\n" +
	"\n" +
	"TLEForward\x12\x18\n" +
	"\acrossed\x18\x01 \x01(\bR\acrossed\x12\x19\n" +
	"\btime_utc\x18\x02 \x01(\tR\atimeUtc\x12)\n" +
	"\x11time_from_start_s\x18\x03 \x01(\x01R\x0etimeFromStartS\x12#\n" +
	"\runcertainty_s\x18\x04 \x01(\x01R\funcertaintyS\x1a\x92\x01\n" +
	"\vPhysicsDrag\x12\x18\n" +
	"\acrossed\x18\x01 \x01(\bR\acrossed\x12\x19\n" +
	"\btime_utc\x18\x02 \x01(\tR\atimeUtc\x12)\n" +
	"\x11time_from_start_s\x18\x03 \x01(\x01R\x0etimeFromStartS\x12#\n" +
	"\runcertainty_s\x18\x04 \x01(\x01R\funcertaintyS\x1a\xdb\x01\n" +
	"\x04Meta\x12'\n" +
	"\x0fpoints_returned\x18\x01 \x01(\rR\x0epointsReturned\x12)\n" +
	"\x10points_generated\x18\x02 \x01(\rR\x0fpointsGenerated\x12%\n" +
	"\x0eskipped_frames\x18\x03 \x01(\rR\rskippedFrames\x12\"\n" +
	"\rtle_epoch_utc\x18\x04 \x01(\tR\vtleEpochUtc\x124\n" +
	"\x17out_of_tle_epoch_window\x18\x05 \x01(\bR\x13outOfTleEpochWindow2\x7f\n" +
	"\x1fSatelliteEarthSimulationService\x12\\\n" +
	"\rRunSimulation\x12$.SatelliteEarthSimulation.SimRequest\x1a%.SatelliteEarthSimulation.SimResponseB+Z)github.com/Theossr/Helikos_test/api/protob\x06proto3"

var (
	file_satellite_Earth_simulation_proto_rawDescOnce sync.Once
	file_satellite_Earth_simulation_proto_rawDescData []byte
)

func file_satellite_Earth_simulation_proto_rawDescGZIP() []byte {
	file_satellite_Earth_simulation_proto_rawDescOnce.Do(func() {
		file_satellite_Earth_simulation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_satellite_Earth_simulation_proto_rawDesc), len(file_satellite_Earth_simulation_proto_rawDesc)))
	})
	return file_satellite_Earth_simulation_proto_rawDescData
}

var file_satellite_Earth_simulation_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_satellite_Earth_simulation_proto_goTypes = []any{
	(*SimRequest)(nil),                    // 0: SatelliteEarthSimulation.SimRequest
	(*SimResponse)(nil),                   // 1: SatelliteEarthSimulation.SimResponse
	(*SimRequest_TLE)(nil),                // 2: SatelliteEarthSimulation.SimRequest.TLE
	(*SimResponse_Frame)(nil),             // 3: SatelliteEarthSimulation.SimResponse.Frame
	(*SimResponse_Decay)(nil),             // 4: SatelliteEarthSimulation.SimResponse.Decay
	(*SimResponse_Meta)(nil),              // 5: SatelliteEarthSimulation.SimResponse.Meta
	(*SimResponse_Frame_Geo)(nil),         // 6: SatelliteEarthSimulation.SimResponse.Frame.Geo
	(*SimResponse_Frame_Mag)(nil),         // 7: SatelliteEarthSimulation.SimResponse.Frame.Mag
	(*SimResponse_Decay_TLEForward)(nil),  // 8: SatelliteEarthSimulation.SimResponse.Decay.TLEForward
	(*SimResponse_Decay_PhysicsDrag)(nil), // 9: SatelliteEarthSimulation.SimResponse.Decay.PhysicsDrag
}
var file_satellite_Earth_simulation_proto_depIdxs = []int32{
	2, // 0: SatelliteEarthSimulation.SimRequest.tle:type_name -> SatelliteEarthSimulation.SimRequest.TLE
	3, // 1: SatelliteEarthSimulation.SimResponse.frames:type_name -> SatelliteEarthSimulation.SimResponse.Frame
	4, // 2: SatelliteEarthSimulation.SimResponse.decay:type_name -> SatelliteEarthSimulation.SimResponse.Decay
	5, // 3: SatelliteEarthSimulation.SimResponse.meta:type_name -> SatelliteEarthSimulation.SimResponse.Meta
	6, // 4: SatelliteEarthSimulation.SimResponse.Frame.geo:type_name -> SatelliteEarthSimulation.SimResponse.Frame.Geo
	7, // 5: SatelliteEarthSimulation.SimResponse.Frame.mag:type_name -> SatelliteEarthSimulation.SimResponse.Frame.Mag
	8, // 6: SatelliteEarthSimulation.SimResponse.Decay.tle_forward:type_name -> SatelliteEarthSimulation.SimResponse.Decay.TLEForward
	9, // 7: SatelliteEarthSimulation.SimResponse.Decay.physics_drag:type_name -> SatelliteEarthSimulation.SimResponse.Decay.PhysicsDrag
	0, // 8: SatelliteEarthSimulation.SatelliteEarthSimulationService.RunSimulation:input_type -> SatelliteEarthSimulation.SimRequest
	1, // 9: SatelliteEarthSimulation.SatelliteEarthSimulationService.RunSimulation:output_type -> SatelliteEarthSimulation.SimResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_satellite_Earth_simulation_proto_init() }
func file_satellite_Earth_simulation_proto_init() {
	if File_satellite_Earth_simulation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_satellite_Earth_simulation_proto_rawDesc), len(file_satellite_Earth_simulation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_satellite_Earth_simulation_proto_goTypes,
		DependencyIndexes: file_satellite_Earth_simulation_proto_depIdxs,
		MessageInfos:      file_satellite_Earth_simulation_proto_msgTypes,
	}.Build()
	File_satellite_Earth_simulation_proto = out.File
	file_satellite_Earth_simulation_proto_goTypes = nil
	file_satellite_Earth_simulation_proto_depIdxs = nil
}
